
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '09da89c0af5c'
down_revision = 'f372bdf920a2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('providers', sa.Column('total_bookings', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('providers', 'total_bookings')
    # ### end Alembic commands ###\"\"\"user_type->value
    
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '09da89c0af5c'
down_revision = 'f372bdf920a2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('providers', sa.Column('total_bookings', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('providers', 'total_bookings')
    # ### end Alembic commands ###