
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c5ec2fb1b3c'
down_revision = '09da89c0af5c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('providers', 'total_bookings')
    op.add_column('users', sa.Column('avatar_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'avatar_url')
    op.add_column('providers', sa.Column('total_bookings', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###\"\"\"Add avatar_url to users