from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68c023a50737'
down_revision = '5c5ec2fb1b3c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###\"\"\"Add avatar_url to users

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68c023a50737'
down_revision = '5c5ec2fb1b3c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###